name: Nightly Sync from Production

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if no changes detected'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  nightly-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup PowerShell
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Sync Vendor Rules (Direct to Main)
      run: |
        echo "🔄 Syncing vendor rules from production (direct to main)..."
        
        # Run sync script for vendor rules only (direct to main)
        pwsh -File scripts/sync-sentinel-changes.ps1 \
          -ResourceGroup "${{ secrets.SENTINEL_RG_PROD }}" \
          -WorkspaceName "${{ secrets.SENTINEL_WS_PROD }}" \
          -Environment "prod" \
          -VendorRulesOnly:$true \
          -ForceSync:${{ inputs.force_sync || false }}

    - name: Check for vendor rule changes
      id: check-vendor-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "vendor-changes=true" >> $GITHUB_OUTPUT
          echo "📝 Vendor rule changes detected"
          git status --porcelain
        else
          echo "vendor-changes=false" >> $GITHUB_OUTPUT
          echo "✅ No vendor rule changes detected"
        fi

    - name: Commit vendor rule changes to main
      if: steps.check-vendor-changes.outputs.vendor-changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add .
        git commit -m "🔄 Nightly sync vendor rules from production - $(date -u +'%Y-%m-%d %H:%M UTC')"
        git push origin main
        
        echo "✅ Successfully synced vendor rules to main"

    - name: Sync Custom Rules (Feature Branch/PR)
      run: |
        echo "🔄 Checking for custom rules in production that need review..."
        
        # Run sync script for custom rules only (will create feature branch if changes found)
        pwsh -File scripts/sync-sentinel-changes.ps1 \
          -ResourceGroup "${{ secrets.SENTINEL_RG_PROD }}" \
          -WorkspaceName "${{ secrets.SENTINEL_WS_PROD }}" \
          -Environment "prod" \
          -CreateBranch:$true \
          -ForceSync:${{ inputs.force_sync || false }}

    - name: Check for custom rule changes
      id: check-custom-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "custom-changes=true" >> $GITHUB_OUTPUT
          echo "📝 Custom rule changes detected - will create feature branch"
          git status --porcelain
        else
          echo "custom-changes=false" >> $GITHUB_OUTPUT
          echo "✅ No custom rule changes detected"
        fi

    - name: Generate branch name for custom rules
      id: custom-branch-name
      if: steps.check-custom-changes.outputs.custom-changes == 'true'
      run: |
        TIMESTAMP=$(date -u +'%Y%m%d-%H%M%S')
        BRANCH_NAME="nightly/custom-rules-$TIMESTAMP"
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "📝 Generated branch name: $BRANCH_NAME"

    - name: Create Pull Request for custom rules
      if: steps.check-custom-changes.outputs.custom-changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.custom-branch-name.outputs.branch-name }}
        base: main
        title: "🔄 Nightly Sync: Custom Rules from Production - $(date -u +'%Y-%m-%d')"
        body: |
          ## Nightly Sync: Custom Rules Detected in Production
          
          ⚠️ **Custom rules found in production that are not in the repository**
          
          This PR contains custom rules that were detected in the production Sentinel environment during the nightly sync. These rules may have been created directly in the portal and need review.
          
          **Generated:** $(date -u +'%Y-%m-%d %H:%M UTC')  
          **Branch:** ${{ steps.custom-branch-name.outputs.branch-name }}
          **Environment:** Production
          
          ### What this means
          - Custom rules were found in production that don't exist in the repository
          - These may be legitimate rules created by engineers or clients
          - Or they may be unauthorized changes that need investigation
          
          ### Next Steps
          1. **Review the changes** in this PR
          2. **Verify the rules** are legitimate and authorized
          3. **Test the rules** if needed
          4. **Approve and merge** if the rules should be kept
          5. **Investigate** if the rules are unauthorized
          
          ### Prevention
          - Ensure all rule creation goes through the proper workflow
          - Use the manual sync workflow for authorized portal changes
          - Monitor production for unauthorized rule creation
          
          **Note:** This is an automated nightly sync. Please review and take appropriate action.
        commit-message: "🔄 Nightly sync custom rules from production - $(date -u +'%Y-%m-%d %H:%M UTC')"
        delete-branch: false

    - name: No changes notification
      if: steps.check-vendor-changes.outputs.vendor-changes == 'false' && steps.check-custom-changes.outputs.custom-changes == 'false'
      run: |
        echo "ℹ️ No changes detected in production environment - no sync needed"
